import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import signinImage from "../public/imagesignin.jpg";
import { TextField } from "@mui/material";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Laranext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.signin}>
        <section className={styles["signin__box"]}>
          <div className={styles["signin__left"]}>
            <Image
              src={signinImage}
              alt="Picture of the author"
              // width={400}
              // height={400}
              blurDataURL="data:..."
              placeholder="blur" // Optional blur-up while loading
              priority
              layout="responsive"
            />
          </div>
          <div className={styles["signin__right"]}>
            <form className={styles["signin__form"]}>
              <p className={styles["signin__welcome"]}>Sign in to Laranext</p>

              <TextField
                id="email"
                label="Email"
                type="text"
                // autoComplete="current-password"
                variant="standard"
                autoComplete="off"
              />
              <TextField
                id="filled-password-input"
                label="Password"
                type="password"
                autoComplete="current-password"
                variant="standard"
              />

              <p className={styles["signin__reset"]}>Forget password?</p>

              <button type="submit" className={styles["signin__btn"]}>
                Sign in
              </button>

              <p className={styles["signin__account"]}>
                New user? Create a new <Link href="/register"> Account </Link>
              </p>
            </form>
          </div>
        </section>
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
};

export default Home;
