import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import signinImage from "../public/imagesignin.jpg";
import { TextField } from "@mui/material";
import Link from "next/link";
import * as Yup from "yup";
import { useMutation } from "react-query";
import { Formik, Field, Form, ErrorMessage, useFormik } from "formik";
import axios from "axios";

interface ISignup {
  firstname: string;
  lastname: string;
  email: string;
  password: string;
  passwordConfirm: string;
}

const initialValues: ISignup = {
  firstname: "",
  lastname: "",
  email: "",
  password: "",
  passwordConfirm: "",
};

const validationSchema = Yup.object({
  firstname: Yup.string().min(2, "Must be at least two characteres").required("Required"),
  lastname: Yup.string().min(2, "Must be at least two characteres").required("Required"),
  email: Yup.string().email("Invalid email address").required("Required"),
  password: Yup.string().min(5, "Must be at least five characteres").required("Required"),
  passwordConfirm: Yup.string()
    .min(5, "Must be at least five characteres")
    .oneOf([Yup.ref("password")], "Passwords must be the same")
    .required("Required"),
});

const Home: NextPage = () => {
  const formik = useFormik({
    initialValues,
    validationSchema: validationSchema,
    onSubmit: values => {
      alert(JSON.stringify(values, null, 2));
      mutation.mutate(values);
    },
  });

  const mutation = useMutation(
    (signup: ISignup) => {
      return axios.post("http://larasar.modemb.com/api/register", signup);
    },
    {
      onSuccess: data => {
        console.log(data);
      },
    }
  );

  if (mutation.isIdle) {
    console.log(mutation.status);
  }
  return (
    <div>
      <Head>
        <title>Laranext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.signin}>
        <section className={styles["signin__box"]}>
          <div className={styles["signin__left"]}>
            <Image
              src={signinImage}
              alt="Picture of the author"
              blurDataURL="data:..."
              placeholder="blur" // Optional blur-up while loading
              priority
              layout="responsive"
            />
          </div>
          <div className={styles["signin__right"]}>
            <form className={styles["signin__form"]} onSubmit={formik.handleSubmit}>
              <p className={styles["signin__welcome"]}>Register to Laranext</p>

              <TextField
                id="firstname"
                name="firstname"
                label="Firstname"
                type="text"
                variant="standard"
                autoComplete="off"
                value={formik.values.firstname}
                onChange={formik.handleChange}
                error={formik.touched.firstname && Boolean(formik.errors.firstname)}
                helperText={formik.touched.firstname && formik.errors.firstname}
              />
              <TextField
                id="lastname"
                name="lastname"
                label="Lastname"
                type="text"
                variant="standard"
                autoComplete="off"
                value={formik.values.lastname}
                onChange={formik.handleChange}
                error={formik.touched.lastname && Boolean(formik.errors.lastname)}
                helperText={formik.touched.lastname && formik.errors.lastname}
              />
              <TextField
                id="email"
                name="email"
                label="Email"
                type="email"
                variant="standard"
                autoComplete="off"
                value={formik.values.email}
                onChange={formik.handleChange}
                error={formik.touched.email && Boolean(formik.errors.email)}
                helperText={formik.touched.email && formik.errors.email}
              />
              <TextField
                id="password"
                name="password"
                label="Password"
                type="password"
                autoComplete="current-password"
                variant="standard"
                value={formik.values.password}
                onChange={formik.handleChange}
                error={formik.touched.password && Boolean(formik.errors.password)}
                helperText={formik.touched.password && formik.errors.password}
              />
              <TextField
                id="passwordConfirm"
                name="passwordConfirm"
                label="Confirm Password"
                type="password"
                autoComplete="current-password"
                variant="standard"
                value={formik.values.passwordConfirm}
                onChange={formik.handleChange}
                error={formik.touched.passwordConfirm && Boolean(formik.errors.passwordConfirm)}
                helperText={formik.touched.passwordConfirm && formik.errors.passwordConfirm}
              />

              <p className={styles["signin__reset"]}>Forget password?</p>

              <button type="submit" className={styles["signin__btn"]}>
                Sign in
              </button>

              <p className={styles["signin__account"]}>
                Go to <Link href="/">Sing in</Link>
              </p>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
